name: Revive Daily Report

on:
  schedule:
    # UTC = 台灣時間 - 8
    - cron: "30 16 * * *"   # 台灣每天 00:30 → 抓昨天
    - cron: "20 * * * *"    # 每小時第 20 分觸發
  workflow_dispatch:         # 可手動觸發

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Revive Report
        env:
          REVIVE_USER: ${{ secrets.REVIVE_USER }}
          REVIVE_PASS: ${{ secrets.REVIVE_PASS }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: node index.js
